apiVersion: v1
kind: Service
metadata:
  name: banking-app-frontend
spec:
  selector:
    app: banking-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-backend
spec:
  selector:
    app: banking-app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
